[build-system]
requires = ['setuptools>=42.0', 'wheel']
build-backend = "setuptools.build_meta"

requires-python = ">=3.8"


[tool.pytest.ini_options]
testpaths = ["tests"]


[tool.mypy]
mypy = "src"
ignore_missing_imports = true